# Generated by Django 5.2.1 on 2025-05-31 08:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField()),
                ('columns', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('company', models.CharField(default='Unknown', max_length=100)),
                ('dos', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Service')),
                ('dosym', models.CharField(default='Unknown', max_length=7)),
                ('run_number', models.CharField(default='Unknown', max_length=20)),
                ('inc_number', models.CharField(default='Unknown', max_length=20)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('prim_pay', models.CharField(default='Unknown', max_length=100)),
                ('pri_payor_category', models.CharField(default='Unknown', max_length=100)),
                ('cur_pay', models.CharField(default='Unknown', max_length=100)),
                ('cur_pay_category', models.CharField(default='Unknown', max_length=100)),
                ('schedule_track', models.CharField(default='Unknown', max_length=100)),
                ('event_step', models.CharField(default='Unknown', max_length=100)),
                ('coll', models.CharField(default='NO', max_length=10)),
                ('gross_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contr_allow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_adjustments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('write_offs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refunds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aging_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('last_event_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('ordering_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.CharField(default='Unknown', max_length=50)),
                ('call_type', models.CharField(default='Unknown', max_length=50)),
                ('priority', models.CharField(default='Unknown', max_length=50)),
                ('call_type_priority', models.CharField(default='Unknown', max_length=100)),
                ('primary_icd', models.CharField(default='Unknown', max_length=20)),
                ('loaded_miles', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('pickup_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_modifier', models.CharField(default='Unknown', max_length=10)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_city', models.CharField(default='Unknown', max_length=100)),
                ('pickup_state', models.CharField(default='NA', max_length=2)),
                ('pickup_zip', models.CharField(default='00000', max_length=10)),
                ('dropoff_facility', models.CharField(default='Unknown', max_length=100)),
                ('dropoff_modifier', models.CharField(default='Unknown', max_length=10)),
                ('dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_city', models.CharField(default='Unknown', max_length=100)),
                ('dropoff_state', models.CharField(default='NA', max_length=2)),
                ('dropoff_zip', models.CharField(default='00000', max_length=15)),
                ('import_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('import_date_ym', models.CharField(default='Unknown', max_length=7)),
                ('med_nec', models.CharField(default='Unknown', max_length=10)),
                ('accident_type', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_group', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('last_modified_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('last_modified_by', models.CharField(default='Unknown', max_length=100)),
                ('team', models.CharField(default='Unknown', max_length=100)),
                ('job', models.CharField(default='Unknown', max_length=50)),
                ('emsmart_id', models.CharField(default='Unknown', max_length=20)),
                ('prior_auth', models.CharField(blank=True, max_length=100, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='rcm_app.excelupload')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('avg_claim_rate_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heard_about_us', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
