# Generated by Django 5.2.1 on 2025-06-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Provider', 'Healthcare Provider'), ('Billing', 'Billing Company')], max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('avg_monthly_claims', models.PositiveIntegerField()),
                ('avg_annual_claims', models.PositiveIntegerField()),
                ('avg_claim_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_plan', models.CharField(choices=[('FTE', 'FTE-based'), ('Transaction', 'Per-Transaction'), ('Percentage', 'Percentage of Collections'), ('OldAR', 'Old AR Recovery')], max_length=20)),
                ('plan_parameter', models.CharField(max_length=100)),
                ('sla_target', models.CharField(blank=True, max_length=100, null=True)),
                ('qa_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('default_sla', models.CharField(blank=True, max_length=100, null=True)),
                ('default_qa_sampling', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.client', verbose_name='Client Name / Acc Name'),
        ),
        migrations.CreateModel(
            name='SOWAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Primary', 'Primary Analyst'), ('Secondary', 'Backup Analyst'), ('QA', 'Quality Auditor')], max_length=20)),
                ('target_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('ramp_up_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.employee')),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.sow')),
            ],
        ),
    ]
