# Generated by Django 5.2.1 on 2025-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0002_remove_exceldata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name / Acc Name')),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ramp_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ramp %')),
            ],
        ),
    ]
