# Generated by Django 5.2.2 on 2025-06-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0003_client_notes_employee_active_employee_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audited_on', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outcome', models.CharField(choices=[('Pass', 'Pass'), ('Minor Error', 'Minor Error'), ('Major Error', 'Major Error'), ('Fail', 'Fail')], max_length=50)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rebuttal_status', models.CharField(choices=[('None', 'None'), ('Disputed', 'Disputed'), ('Resolved', 'Resolved')], default='None', max_length=20)),
                ('rebuttal_comments', models.TextField(blank=True, null=True)),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits_done', to='rcm_app.employee')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcm_app.exceldata')),
            ],
        ),
    ]
