# Generated by Django 5.2.1 on 2025-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0003_employeetarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetarget',
            name='ramp_percentage',
        ),
        migrations.AddField(
            model_name='employeetarget',
            name='ramp_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
