# Generated by Django 5.2.1 on 2025-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0004_qaaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
