# Generated by Django 5.2.1 on 2025-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0005_exceldata_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='dosym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
