# Generated by Django 5.2.1 on 2025-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0006_alter_exceldata_dosym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='import_date_ym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
